CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '${DB_REPL_PASSWORD}';

ALTER USER postgres WITH PASSWORD 'Qq12345';

CREATE DATABASE ${DB_DATABASE};

\c ${DB_DATABASE};

CREATE TABLE IF NOT EXISTS phone_numbers (
    id SERIAL PRIMARY KEY,
    value VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS emails (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL
);
