# Installig python3
FROM python:3.11.8

# Setting workdir
WORKDIR /bot

# Copy requirements.txt to workdir
COPY . .

# Requirements installation
RUN pip install --no-cache-dir -r requirements.txt

RUN apt update && apt install coreutils

# Bot run
CMD ["python", "./bot.py"]
